<?php
require_once app_path('Locx/auth.php'); exigir_login();
require_once app_path('Locx/whatsapp.php');
$pages=modulos_sistema(); $page=$_GET['page'] ?? 'dashboard'; if(!isset($pages[$page])) $page='dashboard'; exigir_perm($page,'visualizar');
$msg=''; $lojas=$pdo->query('SELECT * FROM lojas ORDER BY nome')->fetchAll();
function fetch1($pdo,$sql,$params=[]){$st=$pdo->prepare($sql);$st->execute($params);$r=$st->fetch(PDO::FETCH_ASSOC);return $r?:[];}
function scalar($pdo,$sql,$params=[]){$r=fetch1($pdo,$sql,$params);return array_values($r)[0]??0;}
if($_SERVER['REQUEST_METHOD']==='POST'){
  $acao=$_POST['acao'] ?? '';
  try{
    if($acao==='cliente_salvar'){ exigir_perm('clientes', !empty($_POST['id'])?'editar':'criar');
      $foto=upload_file('foto_cliente'); $doc=upload_file('foto_documento'); $comp=upload_file('comprovante_residencia');
      if(!empty($_POST['id'])){$st=$pdo->prepare('UPDATE clientes SET loja_id=?,nome=?,cpf=?,rg=?,cnh=?,endereco=?,telefone=?,whatsapp=?,email=?,status=? WHERE id=?');$st->execute([$_POST['loja_id']?:null,$_POST['nome'],$_POST['cpf'],$_POST['rg'],$_POST['cnh'],$_POST['endereco'],$_POST['telefone'],$_POST['whatsapp'],$_POST['email'],$_POST['status'],$_POST['id']]);}
      else{$st=$pdo->prepare('INSERT INTO clientes (loja_id,nome,cpf,rg,cnh,endereco,telefone,whatsapp,email,status,foto_cliente,foto_documento,comprovante_residencia) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)');$st->execute([$_POST['loja_id']?:null,$_POST['nome'],$_POST['cpf'],$_POST['rg'],$_POST['cnh'],$_POST['endereco'],$_POST['telefone'],$_POST['whatsapp'],$_POST['email'],$_POST['status'],$foto,$doc,$comp]);}
      $msg='Cliente salvo com sucesso.';
    }
    if($acao==='moto_salvar'){ exigir_perm('motos', !empty($_POST['id'])?'editar':'criar');
      if(!empty($_POST['id'])){$st=$pdo->prepare('UPDATE motocicletas SET loja_id=?,modelo=?,marca=?,ano=?,placa=?,renavam=?,chassi=?,data_aquisicao=?,seguro=?,rastreador=?,status_operacional=? WHERE id=?'); $st->execute([$_POST['loja_id'],$_POST['modelo'],$_POST['marca'],$_POST['ano'],$_POST['placa'],$_POST['renavam'],$_POST['chassi'],$_POST['data_aquisicao'],$_POST['seguro'],$_POST['rastreador'],$_POST['status_operacional'],$_POST['id']]);}
      else{$st=$pdo->prepare('INSERT INTO motocicletas (loja_id,modelo,marca,ano,placa,renavam,chassi,data_aquisicao,seguro,rastreador,status_operacional) VALUES (?,?,?,?,?,?,?,?,?,?,?)'); $st->execute([$_POST['loja_id'],$_POST['modelo'],$_POST['marca'],$_POST['ano'],$_POST['placa'],$_POST['renavam'],$_POST['chassi'],$_POST['data_aquisicao'],$_POST['seguro'],$_POST['rastreador'],$_POST['status_operacional']]);}
      $msg='Motocicleta salva com sucesso.';
    }
    if($acao==='contrato_salvar'){ exigir_perm('contratos','criar');
      $st=$pdo->prepare('INSERT INTO contratos (cliente_id,motocicleta_id,loja_id,data_inicio,valor_contratado,forma_cobranca,status,historico_alteracoes) VALUES (?,?,?,?,?,?,?,?)');
      $st->execute([$_POST['cliente_id'],$_POST['motocicleta_id'],$_POST['loja_id'],$_POST['data_inicio'],$_POST['valor_contratado'],$_POST['forma_cobranca'],$_POST['status'],'Contrato criado em '.date('d/m/Y H:i')]);
      $pdo->prepare('UPDATE motocicletas SET status_operacional="alugada" WHERE id=?')->execute([$_POST['motocicleta_id']]); $msg='Contrato criado.';
    }
    if($acao==='cobranca_salvar'){ exigir_perm('financeiro','criar');
      $contrato=fetch1($pdo,'SELECT * FROM contratos WHERE id=?',[$_POST['contrato_id']]);
      $st=$pdo->prepare('INSERT INTO cobrancas (contrato_id,cliente_id,loja_id,vencimento,valor_principal,valor_atualizado,status,pix_copia_cola,whatsapp_status) VALUES (?,?,?,?,?,?,?,?,?)');
      $pix='PIX-LOCX-'.date('YmdHis').'-'.rand(1000,9999);
      $st->execute([$contrato['id'],$contrato['cliente_id'],$contrato['loja_id'],$_POST['vencimento'],$_POST['valor_principal'],$_POST['valor_principal'],'aberta',$pix,'pendente']);
      $novaCobrancaId=$pdo->lastInsertId();
      $retPix=pagbank_criar_pix($pdo,$novaCobrancaId);
      $msg=!empty($retPix['ok'])?'Cobrança criada e PIX PagBank gerado.':'Cobrança criada. PagBank: '.($retPix['erro']??'PIX não gerado');
    }
    if($acao==='pagamento_salvar'){ exigir_perm('financeiro','editar');
      $pdo->beginTransaction();
      $pdo->prepare('INSERT INTO pagamentos (cobranca_id,valor,forma,pago_em) VALUES (?,?,?,?)')->execute([$_POST['cobranca_id'],$_POST['valor'],$_POST['forma'],date('Y-m-d H:i:s')]);
      $c=fetch1($pdo,'SELECT * FROM cobrancas WHERE id=?',[$_POST['cobranca_id']]); $pago=(float)$c['valor_pago']+(float)$_POST['valor']; $atual=valor_atualizado($c['valor_principal'],$pago,$c['vencimento']); $status=$pago >= (float)$c['valor_principal'] ? 'paga' : 'parcial';
      $pdo->prepare('UPDATE cobrancas SET valor_pago=?,valor_atualizado=?,status=?,whatsapp_status=IF(?="paga","conciliado",whatsapp_status),atualizado_em=NOW() WHERE id=?')->execute([$pago,$atual,$status,$status,$_POST['cobranca_id']]);
      $pdo->commit(); $msg='Pagamento registrado.';
    }
    if($acao==='whatsapp_log'){ exigir_perm('cobrancas','editar');
      $pdo->prepare('INSERT INTO cobranca_logs (cobranca_id,tipo,mensagem) VALUES (?,?,?)')->execute([$_POST['cobranca_id'],$_POST['tipo'],$_POST['mensagem']]);
      $pdo->prepare('UPDATE cobrancas SET whatsapp_status="enviado" WHERE id=?')->execute([$_POST['cobranca_id']]); $msg='Histórico de cobrança registrado.';
    }
    if($acao==='whatsapp_config_salvar'){ exigir_perm('whatsapp','editar');
      $modo=$_POST['modo'] ?? 'demo';
      $ativo=(($_POST['ativo'] ?? '1')==='1')?1:0;
      $st=$pdo->prepare('INSERT INTO whatsapp_config (id,modo,phone_number_id,access_token,verify_token,template_cobranca,template_lembrete,template_bloqueio,ativo,atualizado_em) VALUES (1,?,?,?,?,?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE modo=VALUES(modo),phone_number_id=VALUES(phone_number_id),access_token=VALUES(access_token),verify_token=VALUES(verify_token),template_cobranca=VALUES(template_cobranca),template_lembrete=VALUES(template_lembrete),template_bloqueio=VALUES(template_bloqueio),ativo=VALUES(ativo),atualizado_em=NOW()');
      $st->execute([$modo,$_POST['phone_number_id'],$_POST['access_token'],$_POST['verify_token'],$_POST['template_cobranca'],$_POST['template_lembrete'],$_POST['template_bloqueio'],$ativo]);
      $msg='Configurações do WhatsApp salvas.';
    }
    if($acao==='whatsapp_testar'){ exigir_perm('whatsapp','editar');
      $ret=whatsapp_testar_conexao($pdo);
      $msg=!empty($ret['ok']) ? ($ret['mensagem'] ?? 'Conexão com o WhatsApp validada.') : 'Erro no teste WhatsApp: '.($ret['erro'] ?? 'falha desconhecida');
    }
    if($acao==='whatsapp_enviar_cobranca'){ exigir_perm('inadimplencia','editar');
      $ret=whatsapp_enviar_cobranca($pdo,(int)$_POST['cobranca_id']);
      $msg=!empty($ret['ok']) ? 'Cobrança enviada pelo WhatsApp.' : 'Erro ao enviar WhatsApp: '.($ret['erro'] ?? 'falha desconhecida');
    }
    if($acao==='pagbank_salvar' || $acao==='pagbank_testar'){ exigir_perm('pagbank','editar');
      $modo = $_POST['modo'] ?? 'demo';
      // Normaliza valores antigos eventualmente salvos manualmente no banco.
      if(in_array($modo, ['api oficial','oficial','api_oficial'], true)) $modo = 'api';
      if(!in_array($modo, ['demo','api'], true)) $modo = 'demo';
      $ambiente = $_POST['ambiente'] ?? 'sandbox';
      if(!in_array($ambiente, ['sandbox','producao'], true)) $ambiente = 'sandbox';
      $ativo = (($_POST['ativo'] ?? '1') === '1') ? 1 : 0;
      $webhook = trim($_POST['webhook_url'] ?? '') ?: pagbank_webhook_padrao();
      $merchant = trim($_POST['merchant_reference'] ?? '') ?: 'LOCX';
      $st=$pdo->prepare('INSERT INTO pagbank_config (id,modo,ambiente,client_id,client_secret,access_token,webhook_url,merchant_reference,ativo,atualizado_em)
        VALUES (1,?,?,?,?,?,?,?,?,NOW())
        ON DUPLICATE KEY UPDATE modo=VALUES(modo),ambiente=VALUES(ambiente),client_id=VALUES(client_id),client_secret=VALUES(client_secret),access_token=VALUES(access_token),webhook_url=VALUES(webhook_url),merchant_reference=VALUES(merchant_reference),ativo=VALUES(ativo),atualizado_em=NOW()');
      $st->execute([$modo,$ambiente,trim($_POST['client_id'] ?? ''),trim($_POST['client_secret'] ?? ''),trim($_POST['access_token'] ?? ''),$webhook,$merchant,$ativo]);
      if($acao==='pagbank_testar'){
        $ret=pagbank_testar($pdo);
        if(!empty($ret['ok'])){
          $msg=$ret['mensagem'] ?? (!empty($ret['demo']) ? 'PagBank salvo. Modo demo ativo: nenhuma chamada externa foi feita.' : 'PagBank salvo. Conexão com a API PagBank realizada com sucesso.');
        }else{
          $msg='PagBank salvo, mas o teste falhou. HTTP '.($ret['http_code'] ?? 0).': '.($ret['erro'] ?? 'erro desconhecido');
        }
      }else{
        $msg='Configurações do PagBank salvas com sucesso.';
      }
    }
    if($acao==='pagbank_gerar_pix'){ exigir_perm('financeiro','editar');
      $ret=pagbank_criar_pix($pdo,(int)($_POST['cobranca_id'] ?? 0));
      $msg=!empty($ret['ok']) ? 'PIX PagBank gerado com sucesso para a cobrança.' : 'Erro ao gerar PIX PagBank: '.($ret['erro'] ?? 'falha desconhecida');
    }
    if($acao==='usuario_salvar'){ exigir_perm('usuarios','criar');
      $id=(int)($_POST['id'] ?? 0); $senha=$_POST['senha'] ?? ''; $lojas_sel=$_POST['lojas'] ?? []; $perms=$_POST['perms'] ?? [];
      if($id){ if($senha!==''){$st=$pdo->prepare('UPDATE usuarios SET nome=?,email=?,senha=?,perfil=?,loja_id=?,status=? WHERE id=?');$st->execute([$_POST['nome'],$_POST['email'],password_hash($senha,PASSWORD_DEFAULT),$_POST['perfil'],$_POST['loja_id']?:null,$_POST['status'],$id]);} else {$st=$pdo->prepare('UPDATE usuarios SET nome=?,email=?,perfil=?,loja_id=?,status=? WHERE id=?');$st->execute([$_POST['nome'],$_POST['email'],$_POST['perfil'],$_POST['loja_id']?:null,$_POST['status'],$id]);}}
      else{ if($senha==='') $senha='123456'; $st=$pdo->prepare('INSERT INTO usuarios (nome,email,senha,perfil,loja_id,status) VALUES (?,?,?,?,?,?)'); $st->execute([$_POST['nome'],$_POST['email'],password_hash($senha,PASSWORD_DEFAULT),$_POST['perfil'],$_POST['loja_id']?:null,$_POST['status']]); $id=$pdo->lastInsertId(); }
      $pdo->prepare('DELETE FROM usuario_lojas WHERE usuario_id=?')->execute([$id]); $ins=$pdo->prepare('INSERT INTO usuario_lojas (usuario_id,loja_id) VALUES (?,?)'); foreach($lojas_sel as $lid){$ins->execute([$id,$lid]);}
      $pdo->prepare('DELETE FROM usuario_permissoes WHERE usuario_id=?')->execute([$id]); $inp=$pdo->prepare('INSERT INTO usuario_permissoes (usuario_id,modulo,acao) VALUES (?,?,?)'); foreach($perms as $mod=>$acs){foreach($acs as $ac=>$v){$inp->execute([$id,$mod,$ac]);}}
      $msg='Usuário e permissionamentos salvos.';
    }
  }catch(Exception $e){ if($pdo->inTransaction())$pdo->rollBack(); $msg='Erro: '.$e->getMessage(); }
}
$f=filtro_loja_sql(); $params=$f['params'];
?><!doctype html><html lang="pt-br"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>LocX - <?=e($pages[$page])?></title><link rel="stylesheet" href="assets/css/style.css"></head><body>
<header class="mobile-header"><div class="brand"><div class="brand-icon">LX</div><div><strong>Loc<b>X</b></strong><span>Gestão operacional</span></div></div><button type="button" class="mobile-menu-toggle">☰</button></header><div class="mobile-menu-overlay"></div>
<div class="app"><aside class="sidebar" id="sidebarMenu"><button class="mobile-menu-close">Fechar</button><div class="brand"><div class="brand-icon">LX</div><div><strong>Loc<b>X</b></strong><span>Financeiro e Operacional</span></div></div><div class="nav-title">Navegação</div><nav class="menu"><?php foreach($pages as $k=>$v): if(pode($k,'visualizar')): ?><a class="<?=$page===$k?'active':''?>" href="?page=<?=$k?>"><span><?=icon($k)?></span><?=$v?></a><?php endif; endforeach; ?></nav><div class="sidebar-footer">
    <div class="empresa-logo">
        <img src="assets/img/logo-locx.png" alt="LocX">
    </div>Logado como: <strong><?=e(usuario()['nome'])?></strong><br><?=e(perfil_nome(usuario()['perfil']))?><br><br><a class="btn secondary" href="logout.php">Sair</a></div></aside><main class="main"><header class="topbar"><div><h1><?=e($pages[$page])?></h1><p>Sistema web LocX com gestão multiunidades, operação, financeiro e cobrança.</p></div><div class="toolbar"><a class="btn secondary" href="?page=dashboard">Visão Geral</a></div></header><?php if($msg):?><div class="notice"><strong><?=e($msg)?></strong></div><?php endif;?>
<?php if($page==='dashboard'):
$totMotos=scalar($pdo,'SELECT COUNT(*) FROM motocicletas WHERE 1=1'.$f['sql'],$params);
$alugadas=scalar($pdo,'SELECT COUNT(*) FROM motocicletas WHERE status_operacional="alugada"'.$f['sql'],$params);
$disp=scalar($pdo,'SELECT COUNT(*) FROM motocicletas WHERE status_operacional="disponivel"'.$f['sql'],$params);
$man=scalar($pdo,'SELECT COUNT(*) FROM motocicletas WHERE status_operacional="manutencao"'.$f['sql'],$params);
$recHoje=scalar($pdo,'SELECT COALESCE(SUM(p.valor),0) FROM pagamentos p JOIN cobrancas c ON c.id=p.cobranca_id WHERE DATE(p.pago_em)=CURDATE()'.$f['sql'],$params);
$prevHoje=scalar($pdo,'SELECT COALESCE(SUM(valor_principal),0) FROM cobrancas WHERE vencimento=CURDATE()'.$f['sql'],$params);
$recebidoMes=scalar($pdo,'SELECT COALESCE(SUM(p.valor),0) FROM pagamentos p JOIN cobrancas c ON c.id=p.cobranca_id WHERE MONTH(p.pago_em)=MONTH(CURDATE()) AND YEAR(p.pago_em)=YEAR(CURDATE())'.$f['sql'],$params);
$aReceber=scalar($pdo,'SELECT COALESCE(SUM(valor_atualizado-valor_pago),0) FROM cobrancas WHERE status IN ("aberta","parcial","atrasada")'.$f['sql'],$params);
$atraso=scalar($pdo,'SELECT COALESCE(SUM(valor_atualizado-valor_pago),0) FROM cobrancas WHERE vencimento<CURDATE() AND status<>"paga"'.$f['sql'],$params);
$clientesAtivos=scalar($pdo,'SELECT COUNT(*) FROM clientes WHERE status="ativo"');
$clientesInad=scalar($pdo,'SELECT COUNT(DISTINCT cliente_id) FROM cobrancas WHERE vencimento<CURDATE() AND status<>"paga"');
$labels30=[];$receb30=[];$prev30=[];for($i=29;$i>=0;$i--){$d=date('Y-m-d',strtotime("-$i days"));$labels30[]=date('d/m',strtotime($d));$receb30[]=round((float)scalar($pdo,'SELECT COALESCE(SUM(valor),0) FROM pagamentos WHERE DATE(pago_em)=?',[$d]));$prev30[]=round((float)scalar($pdo,'SELECT COALESCE(SUM(valor_principal),0) FROM cobrancas WHERE vencimento=?',[$d]));}
$lojaLabels=[];$lojaReceb=[];$lojaAtraso=[];foreach($lojas as $l){$lojaLabels[]=$l['nome'];$lojaReceb[]=round((float)scalar($pdo,'SELECT COALESCE(SUM(p.valor),0) FROM pagamentos p JOIN cobrancas c ON c.id=p.cobranca_id WHERE c.loja_id=?',[$l['id']]));$lojaAtraso[]=round((float)scalar($pdo,'SELECT COALESCE(SUM(valor_atualizado-valor_pago),0) FROM cobrancas WHERE loja_id=? AND vencimento<CURDATE() AND status<>"paga"',[$l['id']]));}
$topInad=$pdo->query('SELECT cl.nome, COALESCE(m.placa,"-") placa, DATEDIFF(CURDATE(),MIN(cb.vencimento)) dias, SUM(cb.valor_atualizado-cb.valor_pago) saldo FROM cobrancas cb JOIN clientes cl ON cl.id=cb.cliente_id LEFT JOIN contratos ct ON ct.id=cb.contrato_id LEFT JOIN motocicletas m ON m.id=ct.motocicleta_id WHERE cb.vencimento<CURDATE() AND cb.status<>"paga" GROUP BY cl.id,cl.nome,m.placa ORDER BY saldo DESC LIMIT 6')->fetchAll();
$vencHoje=$pdo->query('SELECT cl.nome, COALESCE(m.placa,"-") placa, cb.vencimento, cb.valor_principal, cb.status FROM cobrancas cb JOIN clientes cl ON cl.id=cb.cliente_id LEFT JOIN contratos ct ON ct.id=cb.contrato_id LEFT JOIN motocicletas m ON m.id=ct.motocicleta_id WHERE cb.vencimento BETWEEN DATE_SUB(CURDATE(), INTERVAL 1 DAY) AND DATE_ADD(CURDATE(), INTERVAL 2 DAY) ORDER BY cb.vencimento ASC LIMIT 8')->fetchAll();
?>
<?php
$cobPagas=scalar($pdo,'SELECT COUNT(*) FROM cobrancas WHERE status="paga"'.$f['sql'],$params);
$cobAbertas=scalar($pdo,'SELECT COUNT(*) FROM cobrancas WHERE status="aberta"'.$f['sql'],$params);
$cobParciais=scalar($pdo,'SELECT COUNT(*) FROM cobrancas WHERE status="parcial"'.$f['sql'],$params);
$cobAtrasadas=scalar($pdo,'SELECT COUNT(*) FROM cobrancas WHERE vencimento<CURDATE() AND status<>"paga"'.$f['sql'],$params);
?>
<div class="cards kpi-row"><div class="metric"><span>Receita recebida no mês</span><strong><?=moeda($recebidoMes)?></strong><small>Pagamentos conciliados</small></div><div class="metric ok"><span>Recebido hoje</span><strong><?=moeda($recHoje)?></strong><small>Baixas do dia</small></div><div class="metric warn"><span>A receber</span><strong><?=moeda($aReceber)?></strong><small>Cobranças abertas/parciais</small></div><div class="metric danger"><span>Inadimplência</span><strong><?=moeda($atraso)?></strong><small><?=$clientesInad?> clientes em atraso</small></div></div>

<div class="chart-row four">
  <div class="panel chart-card"><div class="chart-head"><div><span>RECEITA</span><h2>Composição financeira</h2></div><strong><?=moeda($recebidoMes+$aReceber)?></strong></div><div id="chartReceita" class="donut-premium"></div></div>
  <div class="panel chart-card"><div class="chart-head"><div><span>STATUS</span><h2>Cobranças</h2></div><strong><?=$cobPagas+$cobAbertas+$cobParciais+$cobAtrasadas?></strong></div><div id="chartStatus" class="donut-premium"></div></div>
  <div class="panel chart-card"><div class="chart-head"><div><span>RECEBIDO</span><h2>Por loja</h2></div><strong><?=moeda(array_sum($lojaReceb))?></strong></div><div id="chartRecebidoLojas" class="mini-bars-premium"></div></div>
  <div class="panel chart-card"><div class="chart-head"><div><span>OPERAÇÃO</span><h2>Frota</h2></div><strong><?=$totMotos?> motos</strong></div><div id="chartOperacao" class="donut-premium"></div></div>
</div>

<div class="panel chart-wide-panel"><div class="chart-head"><div><span>EVOLUÇÃO</span><h2>Receita recebida - últimos 30 dias</h2></div><strong><?=moeda(array_sum($receb30))?></strong></div><div id="chartReceb30" class="chart-bars chart-wide clean"></div></div>
<div class="cards"><div class="metric"><span>Total de motos</span><strong><?=$totMotos?></strong></div><div class="metric ok"><span>Disponíveis</span><strong><?=$disp?></strong></div><div class="metric warn"><span>Alugadas</span><strong><?=$alugadas?></strong></div><div class="metric danger"><span>Manutenção</span><strong><?=$man?></strong></div></div>
<div class="grid side dashboard-tables"><div class="panel"><h2>Vencimentos próximos</h2><div class="table-wrap"><table><tr><th>Cliente</th><th>Moto</th><th>Vencimento</th><th>Valor</th><th>Status</th></tr><?php foreach($vencHoje as $r):?><tr><td><?=e($r['nome'])?></td><td><?=e($r['placa'])?></td><td><?=date('d/m/Y',strtotime($r['vencimento']))?></td><td><?=moeda($r['valor_principal'])?></td><td><?=tag_status($r['status'])?></td></tr><?php endforeach;?></table></div></div><div class="panel"><h2>Inadimplência - Top clientes</h2><div class="table-wrap"><table><tr><th>Cliente</th><th>Moto</th><th>Dias</th><th>Saldo</th></tr><?php foreach($topInad as $r):?><tr><td><?=e($r['nome'])?></td><td><?=e($r['placa'])?></td><td><?=max(0,(int)$r['dias'])?></td><td><?=moeda($r['saldo'])?></td></tr><?php endforeach;?></table></div></div></div>
<div class="panel"><h2>Módulos do sistema</h2><div class="module-grid"><?php foreach(['clientes'=>'Cadastro completo e documentos','motos'=>'Frota, status e lojas','contratos'=>'Locação e histórico','financeiro'=>'Recebimentos e pagamentos','cobrancas'=>'WhatsApp e PIX','inadimplencia'=>'Juros e bloqueios','relatorios'=>'Indicadores gerenciais','usuarios'=>'Perfis e permissões'] as $m=>$d):?><a class="module-card" href="?page=<?=$m?>"><i><?=icon($m)?></i><div><strong><?=$pages[$m]?></strong><br><small><?=e($d)?></small></div></a><?php endforeach;?></div></div>
<script>window.addEventListener('load',()=>{locxDonutPremium('chartReceita',[{label:'Recebido',value:<?=round($recebidoMes)?>,color:'#16a34a'},{label:'A receber',value:<?=round($aReceber)?>,color:'#2563eb'},{label:'Em atraso',value:<?=round($atraso)?>,color:'#ef4444'}],'R$');locxDonutPremium('chartStatus',[{label:'Pagas',value:<?=$cobPagas?>,color:'#16a34a'},{label:'Abertas',value:<?=$cobAbertas?>,color:'#2563eb'},{label:'Parciais',value:<?=$cobParciais?>,color:'#f59e0b'},{label:'Atrasadas',value:<?=$cobAtrasadas?>,color:'#ef4444'}]);locxMiniBarsPremium('chartRecebidoLojas',<?=json_encode($lojaLabels)?>,<?=json_encode($lojaReceb)?>,'R$');locxDonutPremium('chartOperacao',[{label:'Alugadas',value:<?=$alugadas?>,color:'#2563eb'},{label:'Disponíveis',value:<?=$disp?>,color:'#16a34a'},{label:'Manutenção',value:<?=$man?>,color:'#f59e0b'},{label:'Outras',value:<?=max(0,$totMotos-$alugadas-$disp-$man)?>,color:'#64748b'}]);locxBars('chartReceb30',<?=json_encode($labels30)?>,<?=json_encode($receb30)?>);});</script>
<?php elseif($page==='clientes'): $edit=!empty($_GET['edit'])?fetch1($pdo,'SELECT * FROM clientes WHERE id=?',[$_GET['edit']]):null; ?>
<div class="grid side"><div class="panel"><h2><?= $edit?'Editar':'Novo' ?> Cliente</h2><form method="post" enctype="multipart/form-data" class="form-grid"><input type="hidden" name="acao" value="cliente_salvar"><input type="hidden" name="id" value="<?=e($edit['id']??'')?>"><label>Loja<select name="loja_id"><option value="">Selecione</option><?php op_lojas($lojas,$edit['loja_id']??''); ?></select></label><label>Nome<input name="nome" required value="<?=e($edit['nome']??'')?>"></label><label>CPF<input name="cpf" value="<?=e($edit['cpf']??'')?>"></label><label>RG<input name="rg" value="<?=e($edit['rg']??'')?>"></label><label>CNH<input name="cnh" value="<?=e($edit['cnh']??'')?>"></label><label>Status<select name="status"><?php foreach(['ativo','inadimplente','bloqueado','encerrado'] as $s):?><option <?=$s==($edit['status']??'ativo')?'selected':''?>><?=$s?></option><?php endforeach;?></select></label><label>Telefone<input name="telefone" value="<?=e($edit['telefone']??'')?>"></label><label>WhatsApp<input name="whatsapp" value="<?=e($edit['whatsapp']??'')?>"></label><label>E-mail<input name="email" value="<?=e($edit['email']??'')?>"></label><label class="span-3">Endereço<textarea name="endereco"><?=e($edit['endereco']??'')?></textarea></label><label>Foto Cliente<input type="file" name="foto_cliente"></label><label>Documento<input type="file" name="foto_documento"></label><label>Comprovante residência<input type="file" name="comprovante_residencia"></label><div class="span-3"><button class="btn">Salvar Cliente</button></div></form></div><div class="panel"><h2>Clientes Cadastrados</h2><?php tabela_clientes($pdo); ?></div></div>
<?php elseif($page==='motos'): $edit=!empty($_GET['edit'])?fetch1($pdo,'SELECT * FROM motocicletas WHERE id=?',[$_GET['edit']]):null; ?>
<div class="grid side"><div class="panel"><h2><?= $edit?'Editar':'Nova' ?> Motocicleta</h2><form method="post" class="form-grid"><input type="hidden" name="acao" value="moto_salvar"><input type="hidden" name="id" value="<?=e($edit['id']??'')?>"><label>Loja<select name="loja_id" required><?php op_lojas($lojas,$edit['loja_id']??''); ?></select></label><label>Marca<input name="marca" value="<?=e($edit['marca']??'')?>"></label><label>Modelo<input name="modelo" required value="<?=e($edit['modelo']??'')?>"></label><label>Ano<input type="number" name="ano" value="<?=e($edit['ano']??'')?>"></label><label>Placa<input name="placa" value="<?=e($edit['placa']??'')?>"></label><label>Renavam<input name="renavam" value="<?=e($edit['renavam']??'')?>"></label><label>Chassi<input name="chassi" value="<?=e($edit['chassi']??'')?>"></label><label>Data aquisição<input type="date" name="data_aquisicao" value="<?=e($edit['data_aquisicao']??'')?>"></label><label>Status<select name="status_operacional"><?php foreach(['disponivel','alugada','manutencao','recuperacao','encerrada'] as $s):?><option value="<?=$s?>" <?=$s==($edit['status_operacional']??'disponivel')?'selected':''?>><?=$s?></option><?php endforeach;?></select></label><label>Seguro<input name="seguro" value="<?=e($edit['seguro']??'')?>"></label><label>Rastreador<input name="rastreador" value="<?=e($edit['rastreador']??'')?>"></label><div class="span-3"><button class="btn">Salvar Moto</button></div></form></div><div class="panel"><h2>Frota Cadastrada</h2><?php tabela_motos($pdo); ?></div></div>
<?php elseif($page==='contratos'): ?>
<div class="grid side"><div class="panel"><h2>Novo Contrato</h2><form method="post" class="form-grid"><input type="hidden" name="acao" value="contrato_salvar"><label>Cliente<select name="cliente_id"><?php foreach($pdo->query('SELECT id,nome FROM clientes ORDER BY nome') as $r)echo '<option value="'.$r['id'].'">'.e($r['nome']).'</option>';?></select></label><label>Moto<select name="motocicleta_id"><?php foreach($pdo->query('SELECT id,placa,modelo FROM motocicletas ORDER BY id DESC') as $r)echo '<option value="'.$r['id'].'">'.e($r['placa'].' - '.$r['modelo']).'</option>';?></select></label><label>Loja<select name="loja_id"><?php op_lojas($lojas,''); ?></select></label><label>Data início<input type="date" name="data_inicio" value="<?=date('Y-m-d')?>"></label><label>Valor contratado<input type="number" step="0.01" name="valor_contratado" value="500.00"></label><label>Forma<select name="forma_cobranca"><option>semanal</option><option>quinzenal</option><option>mensal</option></select></label><label>Status<select name="status"><option>ativo</option><option>suspenso</option><option>encerrado</option></select></label><div class="span-3"><button class="btn">Criar Contrato</button></div></form></div><div class="panel"><h2>Contratos</h2><?php tabela_contratos($pdo); ?></div></div>
<?php elseif(in_array($page,['financeiro','cobrancas','pix'])): ?>
<div class="cards"><div class="metric"><span>Total aberto</span><strong><?=moeda(scalar($pdo,'SELECT COALESCE(SUM(valor_atualizado-valor_pago),0) FROM cobrancas WHERE status<>"paga"'))?></strong></div><div class="metric ok"><span>Pago mês</span><strong><?=moeda(scalar($pdo,'SELECT COALESCE(SUM(valor),0) FROM pagamentos WHERE MONTH(pago_em)=MONTH(CURDATE()) AND YEAR(pago_em)=YEAR(CURDATE())'))?></strong></div><div class="metric warn"><span>Parciais</span><strong><?=scalar($pdo,'SELECT COUNT(*) FROM cobrancas WHERE status="parcial"')?></strong></div><div class="metric danger"><span>Atrasadas</span><strong><?=scalar($pdo,'SELECT COUNT(*) FROM cobrancas WHERE vencimento<CURDATE() AND status<>"paga"')?></strong></div></div>
<div class="grid side"><div class="panel"><h2>Nova Cobrança</h2><form method="post" class="form-grid"><input type="hidden" name="acao" value="cobranca_salvar"><label class="span-2">Contrato<select name="contrato_id"><?php foreach($pdo->query('SELECT c.id,cl.nome,m.placa,c.valor_contratado FROM contratos c JOIN clientes cl ON cl.id=c.cliente_id JOIN motocicletas m ON m.id=c.motocicleta_id ORDER BY c.id DESC') as $r)echo '<option value="'.$r['id'].'">#'.$r['id'].' - '.e($r['nome']).' / '.e($r['placa']).' - '.moeda($r['valor_contratado']).'</option>';?></select></label><label>Vencimento<input type="date" name="vencimento" value="<?=date('Y-m-d')?>"></label><label>Valor<input type="number" step="0.01" name="valor_principal" value="500.00"></label><div class="span-3"><button class="btn">Gerar Cobrança + PIX Demo</button></div></form><hr><h2>Registrar Pagamento</h2><form method="post" class="form-grid"><input type="hidden" name="acao" value="pagamento_salvar"><label class="span-2">Cobrança<select name="cobranca_id"><?php foreach($pdo->query('SELECT cb.*,cl.nome FROM cobrancas cb JOIN clientes cl ON cl.id=cb.cliente_id WHERE cb.status<>"paga" ORDER BY cb.vencimento') as $c)echo '<option value="'.$c['id'].'">#'.$c['id'].' - '.e($c['nome']).' - '.moeda($c['valor_atualizado']-$c['valor_pago']).'</option>';?></select></label><label>Valor Pago<input type="number" step="0.01" name="valor" required></label><label>Forma<select name="forma"><option>pix</option><option>dinheiro</option><option>cartao</option><option>transferencia</option></select></label><div class="span-3"><button class="btn success">Registrar Pagamento</button></div></form></div><div class="panel"><h2><?= $page==='pix'?'Conciliação PIX':'Cobranças' ?></h2><?php tabela_cobrancas($pdo); ?></div></div>
<?php elseif($page==='inadimplencia'): ?>
<div class="panel"><h2>Motor de Inadimplência - Regra LocX</h2><p>Sem pagamento: 10% simples ao dia sobre o valor principal até domingo. Pagamento parcial: 10% composto ao dia sobre o saldo restante até domingo.</p><?php tabela_inadimplencia($pdo); ?></div>
<?php elseif($page==='relatorios'): $lojaDados=[]; foreach($pdo->query('SELECT * FROM lojas ORDER BY id') as $l){$lojaDados[]=['label'=>$l['nome'],'value'=>(float)scalar($pdo,'SELECT COALESCE(SUM(p.valor),0) FROM pagamentos p JOIN cobrancas c ON c.id=p.cobranca_id WHERE c.loja_id=?',[$l['id']])];} ?>
<div class="grid report-charts"><div class="panel report-chart-card"><h2>Faturamento por loja</h2><div id="chartLojas" class="chart-bars report-bars"></div></div><div class="panel report-chart-card"><h2>Clientes por status</h2><div id="donutClientes" class="donut-box report-donut"></div></div></div><div class="panel"><h2>Relatório financeiro detalhado</h2><?php tabela_cobrancas($pdo); ?></div><script>window.addEventListener('load',()=>{locxBars('chartLojas',<?=json_encode(array_column($lojaDados,'label'))?>,<?=json_encode(array_column($lojaDados,'value'))?>);locxDonut('donutClientes',[{label:'Ativos',value:<?=scalar($pdo,'SELECT COUNT(*) FROM clientes WHERE status="ativo"')?>},{label:'Inadimplentes',value:<?=scalar($pdo,'SELECT COUNT(*) FROM clientes WHERE status="inadimplente"')?>},{label:'Bloqueados',value:<?=scalar($pdo,'SELECT COUNT(*) FROM clientes WHERE status="bloqueado"')?>},{label:'Encerrados',value:<?=scalar($pdo,'SELECT COUNT(*) FROM clientes WHERE status="encerrado"')?>}]);});</script>
<?php elseif($page==='lojas'): ?><div class="panel"><h2>Controle por Loja</h2><?php tabela_lojas_resumo($pdo); ?></div>
<?php elseif($page==='usuarios'): $edit=null;$sel_lojas=[];$sel_perms=[]; if(!empty($_GET['edit'])){$edit=fetch1($pdo,'SELECT * FROM usuarios WHERE id=?',[$_GET['edit']]);$sl=$pdo->prepare('SELECT loja_id FROM usuario_lojas WHERE usuario_id=?');$sl->execute([$edit['id']]);foreach($sl as $r)$sel_lojas[]=$r['loja_id'];$sp=$pdo->prepare('SELECT modulo,acao FROM usuario_permissoes WHERE usuario_id=?');$sp->execute([$edit['id']]);foreach($sp as $r)$sel_perms[$r['modulo']][$r['acao']]=true;} ?>
<div class="grid side"><div class="panel"><h2><?= $edit?'Editar':'Novo' ?> Usuário</h2><form method="post" class="form"><input type="hidden" name="acao" value="usuario_salvar"><input type="hidden" name="id" value="<?=e($edit['id']??'')?>"><label>Nome<input name="nome" required value="<?=e($edit['nome']??'')?>"></label><label>E-mail<input type="email" name="email" required value="<?=e($edit['email']??'')?>"></label><label>Senha<input type="password" name="senha" placeholder="<?= $edit?'Manter senha atual':'123456' ?>"></label><label>Perfil<select name="perfil"><?php foreach(['administrador_geral','diretor','financeiro','gerente_loja','atendente','cobranca'] as $p):?><option value="<?=$p?>" <?=$p==($edit['perfil']??'atendente')?'selected':''?>><?=perfil_nome($p)?></option><?php endforeach;?></select></label><label>Loja principal<select name="loja_id"><option value="">Central / Todas</option><?php op_lojas($lojas,$edit['loja_id']??''); ?></select></label><label>Status<select name="status"><option value="ativo" <?=($edit['status']??'ativo')==='ativo'?'selected':''?>>ativo</option><option value="bloqueado" <?=($edit['status']??'')==='bloqueado'?'selected':''?>>bloqueado</option></select></label><h3>Lojas liberadas</h3><div class="checkgrid"><?php foreach($lojas as $l):?><label><input type="checkbox" name="lojas[]" value="<?=$l['id']?>" <?=in_array($l['id'],$sel_lojas)?'checked':''?>> <?=e($l['nome'])?></label><?php endforeach;?></div><h3>Permissões por módulo</h3><div class="perm-table"><table><tr><th>Módulo</th><?php foreach(acoes_sistema() as $a=>$n) echo '<th>'.$n.'</th>'; ?></tr><?php foreach(modulos_sistema() as $m=>$nome):?><tr><td><?=e($nome)?></td><?php foreach(acoes_sistema() as $a=>$n):?><td><input type="checkbox" name="perms[<?=$m?>][<?=$a?>]" value="1" <?=!empty($sel_perms[$m][$a])?'checked':''?>></td><?php endforeach;?></tr><?php endforeach;?></table></div><br><button class="btn">Salvar Usuário</button></form></div><div class="panel"><h2>Usuários</h2><?php tabela_usuarios($pdo); ?></div></div>
<?php elseif($page==='pagbank'): $pcfg=pagbank_config($pdo); $webhook=pagbank_webhook_padrao(); ?>
<div class="grid side">
  <div class="panel"><h2>Configuração PagBank / PIX</h2>
    <form method="post" class="form-grid">
      <input type="hidden" name="acao" value="pagbank_salvar"><input type="hidden" name="id" value="<?=e($pcfg['id']??1)?>">
      <?php $pagModo=($pcfg['modo']??'demo'); if(in_array($pagModo,['api oficial','oficial','api_oficial'],true)) $pagModo='api'; ?>
      <label>Modo<select name="modo"><option value="demo" <?=$pagModo==='demo'?'selected':''?>>demo</option><option value="api" <?=$pagModo==='api'?'selected':''?>>api oficial</option></select></label>
      <label>Ambiente<select name="ambiente"><option value="sandbox" <?=($pcfg['ambiente']??'sandbox')==='sandbox'?'selected':''?>>sandbox</option><option value="producao" <?=($pcfg['ambiente']??'')==='producao'?'selected':''?>>produção</option></select></label>
      <label>Ativo<select name="ativo"><option value="1" <?=!empty($pcfg['ativo'])?'selected':''?>>sim</option><option value="0" <?=empty($pcfg['ativo'])?'selected':''?>>não</option></select></label>
      <label>Client ID<input name="client_id" value="<?=e($pcfg['client_id']??'')?>" placeholder="Opcional / Connect"></label>
      <label>Client Secret<input type="password" name="client_secret" value="<?=e($pcfg['client_secret']??'')?>" placeholder="Opcional / Connect"></label>
      <label class="span-3">Access Token PagBank<input type="password" name="access_token" value="<?=e($pcfg['access_token']??'')?>" placeholder="Bearer token da conta PagBank"></label>
      <label class="span-2">URL Webhook<input name="webhook_url" value="<?=e($pcfg['webhook_url'] ?: $webhook)?>"></label>
      <label>Referência<input name="merchant_reference" value="<?=e($pcfg['merchant_reference']??'LOCX')?>"></label>
      <div class="span-3"><button class="btn">Salvar PagBank</button> <button class="btn secondary" name="acao" value="pagbank_testar">Testar conexão</button></div>
    </form>
  </div>
  <div class="panel"><h2>Status da integração</h2>
    <p><strong>Webhook:</strong><br><code><?=e($pcfg['webhook_url'] ?: $webhook)?></code></p>
    <p><strong>Ambiente:</strong> <?=e($pcfg['ambiente']??'sandbox')?> · <strong>Modo:</strong> <?=e((in_array(($pcfg['modo']??'demo'),['api','api oficial','oficial','api_oficial'],true))?'api oficial':'demo')?></p>
    <p>Use <strong>demo</strong> para testar sem credenciais. Em produção, altere para <strong>api oficial</strong> e informe o Access Token PagBank.</p>
    <p><strong>Atenção:</strong> o webhook precisa usar um endereço público com HTTPS. Endereços localhost não recebem notificações do PagBank.</p>
    <p><a class="btn secondary" href="docs/manual_pagbank.html" target="_blank">Abrir manual PagBank</a></p>
  </div>
</div>
<?php elseif($page==='whatsapp'): $wcfg=whatsapp_config($pdo); ?>
<div class="panel"><h2>WhatsApp Business API</h2><p>Configure a integração oficial da Meta. Use o modo <strong>demo</strong> para testar sem token real. Versão da Graph API: <strong><?=e(whatsapp_graph_version())?></strong>.</p><form method="post" class="form-grid"><input type="hidden" name="acao" value="whatsapp_config_salvar"><label>Modo<select name="modo"><option value="demo" <?=($wcfg['modo']??'demo')==='demo'?'selected':''?>>Demo / Simulado</option><option value="oficial" <?=($wcfg['modo']??'')==='oficial'?'selected':''?>>Oficial - Meta Cloud API</option></select></label><label>Status<select name="ativo"><option value="1" <?=!empty($wcfg['ativo'])?'selected':''?>>Ativo</option><option value="0" <?=empty($wcfg['ativo'])?'selected':''?>>Inativo</option></select></label><label>Phone Number ID<input name="phone_number_id" value="<?=e($wcfg['phone_number_id']??'')?>" placeholder="Ex.: 123456789012345"></label><label class="span-3">Access Token<input type="password" name="access_token" value="<?=e($wcfg['access_token']??'')?>" placeholder="Cole aqui o token da Meta"></label><label>Verify Token<input name="verify_token" value="<?=e($wcfg['verify_token']??'locx_webhook_token')?>"></label><label>Template cobrança<input name="template_cobranca" value="<?=e($wcfg['template_cobranca']??'locx_cobranca_atraso')?>"></label><label>Template lembrete<input name="template_lembrete" value="<?=e($wcfg['template_lembrete']??'locx_lembrete_vencimento')?>"></label><label>Template bloqueio<input name="template_bloqueio" value="<?=e($wcfg['template_bloqueio']??'locx_aviso_bloqueio')?>"></label><div class="span-3"><button class="btn">Salvar Configuração</button></div></form><p><strong>Template de cobrança:</strong> crie na Meta um template em português com 5 variáveis, nesta ordem: cliente, placa, dias em atraso, saldo e PIX copia e cola.</p></div>
<div class="grid side"><div class="panel"><h2>Testar conexão</h2><form method="post"><input type="hidden" name="acao" value="whatsapp_testar"><button class="btn success">Validar credenciais</button></form><p><strong>URL do Webhook:</strong><br><code><?=e(((!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']!=='off')?'https':'http').'://'.($_SERVER['HTTP_HOST'] ?? 'localhost').dirname($_SERVER['SCRIPT_NAME']).'/webhooks/whatsapp.php')?></code></p><p><strong>Atenção:</strong> a Meta também exige um endereço público com HTTPS; localhost serve apenas para testar a tela.</p><p><a class="btn secondary" href="docs/manual_whatsapp.html" target="_blank">Abrir manual WhatsApp</a></p></div><div class="panel"><h2>Últimos envios</h2><?php tabela_whatsapp_logs($pdo); ?></div></div>
<?php elseif($page==='configuracoes'): ?><div class="panel"><h2>Configurações e Integrações Futuras</h2><div class="module-grid"><a class="module-card" href="?page=pagbank"><i><?=icon('pagbank')?></i><div><strong>PagBank</strong><br><small>PIX automático e baixa por webhook</small></div></a><a class="module-card" href="?page=whatsapp"><i><?=icon('whatsapp')?></i><div><strong>WhatsApp API</strong><br><small>Mensagens automáticas</small></div></a><div class="module-card"><i>✍</i><div><strong>Assinatura Digital</strong><br><small>Contratos eletrônicos</small></div></div><div class="module-card"><i>📍</i><div><strong>Rastreadores</strong><br><small>Integração veicular</small></div></div></div></div><?php endif; ?>
</main></div><script src="assets/js/app.js"></script></body></html>
<?php
function tabela_clientes($pdo){echo '<div class="table-wrap"><table><tr><th>Nome</th><th>CPF</th><th>WhatsApp</th><th>Status</th><th>Ações</th></tr>';foreach($pdo->query('SELECT * FROM clientes ORDER BY id DESC LIMIT 120') as $r){echo '<tr><td>'.e($r['nome']).'</td><td>'.e($r['cpf']).'</td><td>'.e($r['whatsapp']).'</td><td>'.tag_status($r['status']).'</td><td><a class="btn secondary" href="?page=clientes&edit='.$r['id'].'">Editar</a></td></tr>';}echo '</table></div>';}
function tabela_motos($pdo){$f=filtro_loja_sql('m');$st=$pdo->prepare('SELECT m.*,l.nome loja FROM motocicletas m JOIN lojas l ON l.id=m.loja_id WHERE 1=1'.$f['sql'].' ORDER BY m.id DESC LIMIT 150');$st->execute($f['params']);echo '<div class="table-wrap"><table><tr><th>Loja</th><th>Placa</th><th>Modelo</th><th>Ano</th><th>Status</th><th>Ações</th></tr>';foreach($st as $r){echo '<tr><td>'.e($r['loja']).'</td><td>'.e($r['placa']).'</td><td>'.e($r['modelo']).'</td><td>'.e($r['ano']).'</td><td>'.tag_status($r['status_operacional']).'</td><td><a class="btn secondary" href="?page=motos&edit='.$r['id'].'">Editar</a></td></tr>';}echo '</table></div>';}
function tabela_contratos($pdo){$f=filtro_loja_sql('c');$st=$pdo->prepare('SELECT c.*,cl.nome cliente,m.placa,l.nome loja FROM contratos c JOIN clientes cl ON cl.id=c.cliente_id JOIN motocicletas m ON m.id=c.motocicleta_id JOIN lojas l ON l.id=c.loja_id WHERE 1=1'.$f['sql'].' ORDER BY c.id DESC LIMIT 120');$st->execute($f['params']);echo '<div class="table-wrap"><table><tr><th>ID</th><th>Cliente</th><th>Moto</th><th>Loja</th><th>Valor</th><th>Status</th></tr>';foreach($st as $r){echo '<tr><td>#'.$r['id'].'</td><td>'.e($r['cliente']).'</td><td>'.e($r['placa']).'</td><td>'.e($r['loja']).'</td><td>'.moeda($r['valor_contratado']).'</td><td>'.tag_status($r['status']).'</td></tr>';}echo '</table></div>';}
function tabela_cobrancas($pdo){
  $f=filtro_loja_sql('cb');
  $st=$pdo->prepare('SELECT cb.*,cl.nome cliente FROM cobrancas cb JOIN clientes cl ON cl.id=cb.cliente_id WHERE 1=1'.$f['sql'].' ORDER BY cb.id DESC LIMIT 160');
  $st->execute($f['params']);
  echo '<div class="table-wrap"><table><tr><th>ID</th><th>Cliente</th><th>Vencimento</th><th>Principal</th><th>Pago</th><th>Atualizado</th><th>PIX/WhatsApp</th><th>PagBank</th><th>Status</th></tr>';
  foreach($st as $r){
    $atual=valor_atualizado($r['valor_principal'],$r['valor_pago'],$r['vencimento']);
    if($r['status']!=='paga' && abs($atual-$r['valor_atualizado'])>0.01){
      $pdo->prepare('UPDATE cobrancas SET valor_atualizado=?, status=IF(vencimento<CURDATE(),"atrasada",status) WHERE id=?')->execute([$atual,$r['id']]);
      $r['valor_atualizado']=$atual;
      if(strtotime($r['vencimento'])<strtotime(date('Y-m-d'))) $r['status']='atrasada';
    }
    $pixInfo = !empty($r['pix_copia_cola']) ? 'PIX gerado' : 'Sem PIX';
    $pagStatus = !empty($r['pagbank_status']) ? tag_status($r['pagbank_status']) : '<span class="tag muted">não gerado</span>';
    echo '<tr><td>#'.$r['id'].'</td><td>'.e($r['cliente']).'</td><td>'.date('d/m/Y',strtotime($r['vencimento'])).'</td><td>'.moeda($r['valor_principal']).'</td><td>'.moeda($r['valor_pago']).'</td><td>'.moeda($r['valor_atualizado']).'</td><td>'.e($pixInfo).' / '.tag_status($r['whatsapp_status']??'pendente').'</td><td><div class="actions"><form method="post" style="display:inline"><input type="hidden" name="acao" value="pagbank_gerar_pix"><input type="hidden" name="cobranca_id" value="'.(int)$r['id'].'"><button class="btn secondary" type="submit">Gerar PIX</button></form></div><br>'.$pagStatus.'</td><td>'.tag_status($r['status']).'</td></tr>';
  }
  echo '</table></div>';
}
function tabela_inadimplencia($pdo){$st=$pdo->query('SELECT cb.*,cl.nome,cl.whatsapp,m.placa FROM cobrancas cb JOIN clientes cl ON cl.id=cb.cliente_id LEFT JOIN contratos ct ON ct.id=cb.contrato_id LEFT JOIN motocicletas m ON m.id=ct.motocicleta_id WHERE cb.vencimento<CURDATE() AND cb.status<>"paga" ORDER BY cb.vencimento ASC');echo '<div class="table-wrap"><table><tr><th>Cliente</th><th>Moto</th><th>Dias</th><th>Saldo Original</th><th>Pago</th><th>Atualizado</th><th>WhatsApp</th></tr>';foreach($st as $r){$dias=dias_atraso_ate_domingo($r['vencimento']);$atual=valor_atualizado($r['valor_principal'],$r['valor_pago'],$r['vencimento']);$wa='https://wa.me/55'.preg_replace('/\D/','',$r['whatsapp']);echo '<tr><td>'.e($r['nome']).'</td><td>'.e($r['placa']).'</td><td>'.$dias.'</td><td>'.moeda($r['valor_principal']).'</td><td>'.moeda($r['valor_pago']).'</td><td>'.moeda($atual).'</td><td><div class="actions"><a class="btn secondary" target="_blank" href="'.$wa.'">Abrir</a><form method="post" style="display:inline"><input type="hidden" name="acao" value="whatsapp_enviar_cobranca"><input type="hidden" name="cobranca_id" value="'.(int)$r['id'].'"><button class="btn success" type="submit">Enviar API</button></form></div></td></tr>';}echo '</table></div>';}
function tabela_whatsapp_logs($pdo){try{$st=$pdo->query('SELECT wl.*,cl.nome cliente FROM whatsapp_logs wl LEFT JOIN clientes cl ON cl.id=wl.cliente_id ORDER BY wl.id DESC LIMIT 80');echo '<div class="table-wrap"><table><tr><th>Data</th><th>Cliente</th><th>Telefone</th><th>Tipo</th><th>Status</th><th>HTTP</th></tr>';foreach($st as $r){echo '<tr><td>'.date('d/m/Y H:i',strtotime($r['criado_em'])).'</td><td>'.e($r['cliente']??'-').'</td><td>'.e($r['telefone']).'</td><td>'.e($r['tipo']).'</td><td>'.tag_status($r['status']).'</td><td>'.e($r['http_code']??'-').'</td></tr>';}echo '</table></div>';}catch(Throwable $e){echo '<div class="empty">Execute atualizar_banco.php para criar as tabelas do WhatsApp.</div>';}}

function tabela_usuarios($pdo){echo '<div class="table-wrap"><table><tr><th>Nome</th><th>E-mail</th><th>Perfil</th><th>Loja principal</th><th>Status</th><th>Ações</th></tr>';foreach($pdo->query('SELECT u.*,l.nome loja FROM usuarios u LEFT JOIN lojas l ON l.id=u.loja_id ORDER BY u.id DESC') as $r){echo '<tr><td>'.e($r['nome']).'</td><td>'.e($r['email']).'</td><td>'.e(perfil_nome($r['perfil'])).'</td><td>'.e($r['loja'] ?: 'Todas / Central').'</td><td>'.tag_status($r['status']).'</td><td><a class="btn secondary" href="?page=usuarios&edit='.$r['id'].'">Editar</a></td></tr>';}echo '</table></div>';}
function tabela_lojas_resumo($pdo){echo '<div class="table-wrap"><table><tr><th>Loja</th><th>Motos</th><th>Alugadas</th><th>Disponíveis</th><th>Recebido</th><th>Em atraso</th></tr>';foreach($pdo->query('SELECT * FROM lojas ORDER BY nome') as $l){$m=scalar($pdo,'SELECT COUNT(*) FROM motocicletas WHERE loja_id=?',[$l['id']]);$a=scalar($pdo,'SELECT COUNT(*) FROM motocicletas WHERE loja_id=? AND status_operacional="alugada"',[$l['id']]);$d=scalar($pdo,'SELECT COUNT(*) FROM motocicletas WHERE loja_id=? AND status_operacional="disponivel"',[$l['id']]);$rec=scalar($pdo,'SELECT COALESCE(SUM(p.valor),0) FROM pagamentos p JOIN cobrancas c ON c.id=p.cobranca_id WHERE c.loja_id=?',[$l['id']]);$at=scalar($pdo,'SELECT COALESCE(SUM(valor_atualizado-valor_pago),0) FROM cobrancas WHERE loja_id=? AND vencimento<CURDATE() AND status<>"paga"',[$l['id']]);echo '<tr><td>'.e($l['nome']).'</td><td>'.$m.'</td><td>'.$a.'</td><td>'.$d.'</td><td>'.moeda($rec).'</td><td>'.moeda($at).'</td></tr>';}echo '</table></div>';}
?>
